name: attendance_app
description: A simple cross-platform attendance app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  excel: ^2.1.0
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  flutter_pdfview: ^1.3.2
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
